### Get games
GET http://localhost:8080/api/game
Authorization: Bearer {{jwt}}

### Get games by name
GET http://localhost:8080/api/game/name/Half
Authorization: Bearer {{jwt}}

### Get game by id
GET http://localhost:8080/api/game/1
Authorization: Bearer {{jwt}}

### Insert game - admin
POST http://localhost:8080/api/game
Authorization: Bearer {{jwtAdmin}}
Content-Type: application/json

{
  "id": null,
  "name": "New Game",
  "description": "Game description",
  "releaseDate": "2023-10-10",
  "positiveRatings": 1423,
  "negativeRatings": 79,
  "averagePlaytime": 832,
  "medianPlaytime": 752,
  "owners": "10000-30000",
  "price": 50.99,
  "categories": [
    {
      "id": 18,
      "name": "Co-op"
    },
    {
      "id": 5,
      "name": "Single-player"
    },
    {
      "id": 10,
      "name": "Partial Controller Support"
    },
    {
      "id": 1,
      "name": "Multi-player"
    }
  ],
  "developers": [
    {
      "id": 176,
      "name": "Ubisoft Montréal"
    },
    {
      "id": 815,
      "name": "and Ubisoft Shanghai"
    },
    {
      "id": 814,
      "name": "Massive Entertainment"
    }
  ],
  "genres": [
    {
      "id": 4,
      "name": "Adventure"
    },
    {
      "id": 1,
      "name": "Action"
    }
  ],
  "platforms": [
    {
      "id": 1,
      "name": "windows"
    }
  ],
  "publishers": [
    {
      "id": 10,
      "name": "Ubisoft"
    }
  ]
}

### Update game - admin
POST http://localhost:8080/api/game
Authorization: Bearer {{jwtAdmin}}
Content-Type: application/json

{
  "id": 1,
  "name": "New Game",
  "description": "Game description",
  "releaseDate": "2023-10-10",
  "positiveRatings": 1423,
  "negativeRatings": 79,
  "averagePlaytime": 832,
  "medianPlaytime": 752,
  "owners": "10000-30000",
  "price": 50.99,
  "categories": [
    {
      "id": 18,
      "name": "Co-op"
    },
    {
      "id": 5,
      "name": "Single-player"
    },
    {
      "id": 10,
      "name": "Partial Controller Support"
    },
    {
      "id": 1,
      "name": "Multi-player"
    }
  ],
  "developers": [
    {
      "id": 176,
      "name": "Ubisoft Montréal"
    },
    {
      "id": 815,
      "name": "and Ubisoft Shanghai"
    },
    {
      "id": 814,
      "name": "Massive Entertainment"
    }
  ],
  "genres": [
    {
      "id": 4,
      "name": "Adventure"
    },
    {
      "id": 1,
      "name": "Action"
    }
  ],
  "platforms": [
    {
      "id": 1,
      "name": "windows"
    }
  ],
  "publishers": [
    {
      "id": 10,
      "name": "Ubisoft"
    }
  ]
}

### Delete game by id - admin
DELETE http://localhost:8080/api/game/1
Authorization: Bearer {{jwtAdmin}}