### Get games
GET http://localhost:8080/api/game
Authorization: Bearer {{jwt}}

### Get games by name
GET http://localhost:8080/api/game/name/Half
Authorization: Bearer {{jwt}}

### Get game by id
GET http://localhost:8080/api/game/1
Authorization: Bearer {{jwt}}

### Insert game - admin
POST http://localhost:8080/api/game
Authorization: Bearer {{jwtAdmin}}
Content-Type: application/json

{
  "id": null,
  "name": "New Game",
  "description": "One of the most popular online action games of all time, Team Fortress Classic features over nine character classes -- from Medic to Spy to Demolition Man -- enlisted in a unique style of online team warfare. Each character class possesses unique weapons, items, and abilities, as teams compete online in a variety of game play modes.",
  "releaseDate": "1999-04-01",
  "positiveRatings": 3318,
  "negativeRatings": 633,
  "averagePlaytime": 277,
  "medianPlaytime": 62,
  "owners": "5000000-10000000",
  "price": 3.99,
  "categories": [
    {
      "id": 2,
      "name": "Online Multi-Player"
    },
    {
      "id": 4,
      "name": "Valve Anti-Cheat enabled"
    },
    {
      "id": 3,
      "name": "Local Multi-Player"
    },
    {
      "id": 1,
      "name": "Multi-player"
    }
  ],
  "developers": [
    {
      "id": 1,
      "name": "Valve"
    }
  ],
  "genres": [
    {
      "id": 1,
      "name": "Action"
    }
  ],
  "platforms": [
    {
      "id": 1,
      "name": "windows"
    },
    {
      "id": 3,
      "name": "linux"
    },
    {
      "id": 2,
      "name": "mac"
    }
  ],
  "publishers": [
    {
      "id": 1,
      "name": "Valve"
    }
  ]
}

### Update game - admin
PUT http://localhost:8080/api/game
Authorization: Bearer {{jwtAdmin}}
Content-Type: application/json

{
  "id": 1,
  "name": "Updated Game",
  "description": "One of the most popular online action games of all time, Team Fortress Classic features over nine character classes -- from Medic to Spy to Demolition Man -- enlisted in a unique style of online team warfare. Each character class possesses unique weapons, items, and abilities, as teams compete online in a variety of game play modes.",
  "releaseDate": "1999-04-01",
  "positiveRatings": 3318,
  "negativeRatings": 633,
  "averagePlaytime": 277,
  "medianPlaytime": 62,
  "owners": "5000000-10000000",
  "price": 3.99,
  "categories": [
    {
      "id": 2,
      "name": "Online Multi-Player"
    },
    {
      "id": 4,
      "name": "Valve Anti-Cheat enabled"
    },
    {
      "id": 3,
      "name": "Local Multi-Player"
    },
    {
      "id": 1,
      "name": "Multi-player"
    }
  ],
  "developers": [
    {
      "id": 1,
      "name": "Valve"
    }
  ],
  "genres": [
    {
      "id": 1,
      "name": "Action"
    }
  ],
  "platforms": [
    {
      "id": 1,
      "name": "windows"
    },
    {
      "id": 3,
      "name": "linux"
    },
    {
      "id": 2,
      "name": "mac"
    }
  ],
  "publishers": [
    {
      "id": 1,
      "name": "Valve"
    }
  ]
}

### Delete game by id - admin
DELETE http://localhost:8080/api/game/1
Authorization: Bearer {{jwtAdmin}}