### Get users - admin
GET http://localhost:8080/api/user
Authorization: Bearer {{jwtAdmin}}

### Get account details
GET http://localhost:8080/api/user/details
Authorization: Bearer {{jwt}}

### Delete account
DELETE http://localhost:8080/api/user
Authorization: Bearer {{jwt}}